name: Create Production Builds
on:
  push:
    branches: ["main"]

jobs:
  build_ios:
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
  submit_ios:
    name: Submit app
    EXPO_DEBUG: "1"
    needs: [build_ios]
    type: submit
    environment: production
    params:
      platform: ios
      profile: production
      build_id: ${{ needs.build_ios.outputs.build_id }}
